### ISSUE TITLE
Gmail Completely Crippled (Error #001)

### ISSUE THREAD

**Issue by TetterkeT** [OneClickLab/ugly-email-extension#38] opened 2024-02-13 18:11 UTC
Using Ugly Email version 4.1.1 on Chrome browser and over the past couple of days I keep getting an "Oops...the system encountered an error (# 001)" message whenever I try to do anything (send, search, switch folders). Disabling the extension eliminates the issue which leads me to believe that there is a problem with the extension.

**Comment by purevertigo** [comment] 2024-02-22 07:14
Yeah, had to disable as it was driving me crazy

**Comment by rbrownejr** [comment] 2024-02-28 02:40
Same issue here:    Oops… the system encountered a problem (#2014).  Disabling the extension works.

What's weird is I have two Google accounts signed into that browser, but it only throws that error on one of the accounts, not the other.

**Comment by trothwell** [comment] 2024-02-28 14:30
Error #2014 for me.

```
Note: Error #2014 is related to a Chrome browser extension. [Disable your Chrome extensions](https://support.google.com/mail/answer/7036382) one at a time to determine which extension is causing the error. The full text of error #2014 is: Oops... the system is experiencing a problem (#2014) - Try again.
```
> https://support.google.com/a/answer/3726730

**Comment by suddenlydoomy** [comment] 2024-02-28 16:04
I'm also getting Error #2014 and by disabling and enabling extensions I've been able to confirm that it's being caused by Ugly Email.

**Comment by aytimothy** [comment] 2024-02-29 20:04
It seems to only affect some accounts from testing; my main account couldn't load at all but all my other accounts could.

**Comment by suddenlydoomy** [comment] 2024-02-29 21:01
> It seems to only affect some accounts from testing; my main account couldn't load at all but all my other accounts could. Maybe some sort of rate limit being hit?

I don't think it's a rate limit, but I can confirm that not all accounts are affected because my Gmail for Business account seizes up with Error #2014 while my personal Gmail account still operates fine.

**Comment by aytimothy** [comment] 2024-02-29 21:19
> personal Gmail account still operates fine

Mine's the opposite; Business is fine, and only one out of all my many personal accounts is affected.

**Comment by jeisner** [comment] 2024-02-29 22:53
Gmail is also suddenly unusable for me as of today, but I was getting a different error all day: "The conversation that you requested could not be loaded."  Also sometimes getting a warning that Gmail was having trouble connecting and I could click "Retry now."

Disabling the extension fixed it.  This is in Chromium on Linux.

**Comment by DavidTre07** [comment] 2024-03-02 15:05
Same from my side: Windows 11 + Edge

**Comment by SkullKill** [comment] 2024-03-05 02:32
started to get "Oops… the system encountered a problem (#2014)" error on my Google Workspace email today too. disabled ugly email, and gmail works fine again.

**Comment by sonnyt** [comment] 2024-03-05 21:32
I think I have a fix!

I am working on it and will have the beta available by tomorrow! 🤞

**Comment by sonnyt** [comment] 2024-03-06 17:22
Can someone help test it? @aytimothy @veriovka @suddenlydoomy @jeisner 
[ugly-email-402.zip](https://github.com/OneClickLab/ugly-email-extension/files/14513421/ugly-email-402.zip)

**Comment by oblivioncth** [comment] 2024-03-06 18:11
If anyone else is unsure how to test: https://developer.chrome.com/docs/extensions/get-started/tutorial/hello-world#load-unpacked

Seems to work for me. No #2014 (which I had previously) and I see that some emails are tagged with the eye, so it appears the extension still functions as well.

**Comment by OrBin** [comment] 2024-03-06 18:39
Same here: No #2014, which I had previously with the version from store.

**Comment by sonnyt** [comment] 2024-03-06 19:02
New fixed version is submitted to Firefox and Chrome Stores for a review. I will keep this issue open until the extension is published and verified!

**Comment by arturododd** [comment] 2024-03-06 19:48
Having the same issue with version 4.1.1, disabling removes the problem.

![WhatsApp Image 2024-03-06 at 13 01 58_781c2389](https://github.com/OneClickLab/ugly-email-extension/assets/6409701/accb11b7-0830-45d6-b140-7431c30248e2)
![WhatsApp Image 2024-03-06 at 13 07 32_46c5bbd9](https://github.com/OneClickLab/ugly-email-extension/assets/6409701/de5add13-3f34-49ba-b3d8-01b0f6723a8b)

Tested with the version here and with the normal version disabled and the error goes away.
![image](https://github.com/OneClickLab/ugly-email-extension/assets/6409701/ce1f3f45-cb6f-4758-afaf-2d4fc6dec2df)
![image](https://github.com/OneClickLab/ugly-email-extension/assets/6409701/ec43a3ab-8154-4717-8e54-cb4a5e84c8f7)
![image](https://github.com/OneClickLab/ugly-email-extension/assets/6409701/ff1f7348-d822-4575-8c13-43e894ad9eb1)

**Comment by codigo47** [comment] 2024-03-07 13:59
It's working fine in Google Chrome Version 123.0.6312.22 (Official Build) beta (64-bit), Ubuntu 22.04.4

**Comment by sonnyt** [comment] 2024-03-07 16:16
Chrome update is approved and published. Everything seems to be working fine so far.

I will close this issue.

Thank you everyone for reporting the issue and help resolving it!

❤️

**Closed by sonnyt** 2024-03-07 16:16 UTC
